name: 'LCOV Summary Reporter'
description: 'Summarize LCOV coverage reports'
author: 'Pre-history'
branding:
  icon: 'pie-chart'
  color: 'green'
inputs:
  github-token:
    description: Github token
    required: false
    default: ${{ github.token }}
  title:
    description: Summary title
    required: false
  lcov-file:
    description: Path to LCOV file
    required: false
    default: './coverage/lcov.info'
  comment-on-pr:
    description: Add Diagram comment to the current PR
    required: false
  working-directory:
    description: Set working directory if project is not in root folder
    required: false
    default: './'
  pie-covered-color:
    description: Color for pie chart covered part
    required: false
    default: '#4CAF50'
  pie-not-covered-color:
    description: Color for pie chart not coverage part
    required: false
    default: '#FF5733'
  debug-lcov:
    description: Debug LCOV file (Show the content of the LCOV file)
    required: false
    default: false
  base-lcov-file:
    description: Path to base branch LCOV file for comparison
    required: false
  detailed-summary:
    description: Generate detailed summary with file breakdown
    required: false
    default: false
  max-files-shown:
    description: Maximum number of files to show in detailed reports
    required: false
    default: '10'
runs:
  using: 'node20'
  main: 'dist/index.js'
