name: 'LCOV Summary Reporter'
description: 'Summarize LCOV coverage reports'
inputs:
  github-token:
    description: Github token
    required: false
    default: ${{ github.token }}
  title:
    description: Summary title
    required: false
  lcov-file:
    description: Path to LCOV file
    required: false
  working-directory:
    description: Set working directory if project is not in root folder
    required: false
    default: './'
runs:
  using: 'node20'
  main: 'dist/index.js'
